require:
  - rubocop-github-rails
  - rubocop-rails

Rails/OutputSafety:
  Enabled: true

Rails/PluralizationGrammar:
  Enabled: true

Rails/RequestReferer:
  Enabled: true
  EnforcedStyle: referrer

Rails/ScopeArgs:
  Enabled: true

Rails/UniqBeforePluck:
  Enabled: true

GitHub/RailsApplicationRecord:
  Enabled: true

GitHub/RailsControllerRenderActionSymbol:
  Enabled: true

GitHub/RailsControllerRenderLiteral:
  Enabled: true

GitHub/RailsControllerRenderPathsExist:
  Enabled: true

GitHub/RailsControllerRenderShorthand:
  Enabled: true

GitHub/RailsRenderInline:
  Enabled: true

GitHub/RailsRenderObjectCollection:
  Enabled: false

GitHub/RailsViewRenderLiteral:
  Enabled: true

GitHub/RailsViewRenderPathsExist:
  Enabled: true

GitHub/RailsViewRenderShorthand:
  Enabled: true

# Exclude Rails ERB files from incompatible cops

Layout/BlockAlignment:
  Exclude:
    - 'app/views/**/*.erb'

Style/For:
  Exclude:
    - 'app/views/**/*.erb'

Style/OneLineConditional:
  Exclude:
    - 'app/views/**/*.erb'

Style/Semicolon:
  Exclude:
    - 'app/views/**/*.erb'

Layout/SpaceInsideParens:
  Exclude:
    - 'app/views/**/*.erb'

Style/StringLiterals:
  Exclude:
    - 'app/views/**/*.erb'

Layout/TrailingEmptyLines:
  Exclude:
    - 'app/views/**/*.erb'

Layout/TrailingWhitespace:
  Exclude:
    - 'app/views/**/*.erb'

Layout/IndentationWidth:
  Exclude:
    - 'app/views/**/*.erb'

Layout/InitialIndentation:
  Exclude:
    - 'app/views/**/*.erb'

Lint/UselessAccessModifier:
  ContextCreatingMethods:
    - concerning
